[tool.poetry]
name = "aspire"
version = "0.1.0"
description = "aspire home challenge"
authors = ["Gabriel"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "^7.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
